/******************************************************************************
*  Generated by PSoC Designer 5.3.2710
******************************************************************************/
#ifndef __PSOCAPI_H
#define __PSOCAPI_H

#include "PSoCGPIOINT.h"
#include "LEDFlashTimer.h"
#include "VR_ADC.h"
#include "VR_PGA.h"

#endif
